#!/bin/bash

# set -x

# PATH=`pwd`/bin:$PATH
if [ -f demo_env.sh ]; then
    . ./demo_env.sh
fi

. env.sh

# export VAULT_TOKEN=${VAULT_ROOT_TOKEN}
export VAULT_ROOT_TOKEN=$VAULT_TOKEN
export MYSQL_HOST=${DB_HOSTNAME}
export MYSQL_TCP_PORT=${DB_PORT}

# clear
cyan "Let's now generate some tokens with the sakila-admin policy"
echo
echo
green "vault token create -policy sakila-admin"
pe "vault token create -policy sakila-admin -format=json > sakila-admin.token"
pe "SAKILA_ADMIN_TOKEN=`jq -r .auth.client_token sakila-admin.token`"
pe "VAULT_TOKEN=$SAKILA_ADMIN_TOKEN vault read auth/token/lookup-self"

# read
# clear
cyan "And use the sakila-admin token to fetch some database credentials"
echo
echo
green "vault read database/creds/sakila-admin"
pe "VAULT_TOKEN=$SAKILA_ADMIN_TOKEN vault read database/creds/sakila-admin -format=json > sakila-admin.creds"
pe "jq . sakila-admin.creds"


# read
# clear
cyan "Let's try those credentials out"
pe "SAKILA_DB_USER=`jq -r .data.username sakila-admin.creds`"
pe "SAKILA_DB_PASS=`jq -r .data.password sakila-admin.creds`"
set -x
mysql -u"$SAKILA_DB_USER" -p"$SAKILA_DB_PASS" sakila -e "show grants;"
set +x
echo
echo
read
cyan "Now let's revoke those credentials and see what happens"
echo "vault token revoke -self"
pe "VAULT_TOKEN=$SAKILA_ADMIN_TOKEN vault token revoke -self"
# read
echo
echo
set -x
mysql -u"$SAKILA_DB_USER" -p"$SAKILA_DB_PASS" sakila -e "show grants;"
set +x
echo
echo
read

clear
cyan "Let's do the same for the sakila-backend policy"
green "This time, however, let's make direct use of the Vault RESTful API"
echo
echo
cat <<EOF | tee sakila-backend.request.json
{
  "policies": ["sakila-backend"]
}
EOF
read

clear
echo
echo
cat <<EOF
curl -s 
  --header "X-Vault-Token: ${VAULT_ROOT_TOKEN}" 
  --request POST 
  --data @sakila-backend.request.json 
  ${VAULT_ADDR}/v1/auth/token/create > sakila-backend.token
EOF

curl -s \
  --header "X-Vault-Token: ${VAULT_ROOT_TOKEN}" \
  --request POST \
  --data @sakila-backend.request.json \
  ${VAULT_ADDR}/v1/auth/token/create > sakila-backend.token
read

# clear
pe "jq . sakila-backend.token"
pe "SAKILA_BACKEND_TOKEN=`jq -r .auth.client_token sakila-backend.token`"

# read
# clear
cyan "And use the sakila-backend token to fetch some database credentials"
echo
echo
echo 'curl -s \
  --header "X-Vault-Token: $SAKILA_BACKEND_TOKEN" \
  ${VAULT_ADDR}/v1/database/creds/sakila-backend > sakila-backend.creds'
curl -s \
  --header "X-Vault-Token: $SAKILA_BACKEND_TOKEN" \
  ${VAULT_ADDR}/v1/database/creds/sakila-backend > sakila-backend.creds

read
# clear
pe "jq . sakila-backend.creds"


read
# clear
cyan "Let's try those credentials out"
pe "SAKILA_DB_USER=`jq -r .data.username sakila-backend.creds`"
pe "SAKILA_DB_PASS=`jq -r .data.password sakila-backend.creds`"
set -x
mysql -u"$SAKILA_DB_USER" -p"$SAKILA_DB_PASS" sakila -e "show grants;"
set +x
echo
echo
read
cyan "Now let's revoke those credentials and see what happens"
echo "vault token revoke -self"
pe "VAULT_TOKEN=$SAKILA_BACKEND_TOKEN vault token revoke -self"
# read
echo
echo
set -x
mysql -u"$SAKILA_DB_USER" -p"$SAKILA_DB_PASS" sakila -e "show grants;"
set +x
